//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVis.ROps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RVis.ROps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzLFB &lt;- rawConnection(rawLFB, open=&apos;rb&apos;)
        ///load(zzLFB).
        /// </summary>
        internal static string FMT_LOAD_FROM_BINARY {
            get {
                return ResourceManager.GetString("FMT_LOAD_FROM_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzSOTB &lt;- rawConnection(raw(0), &quot;r+b&quot;)
        ///save({0}, file=zzSOTB)
        ///seek(zzSOTB, 0, rw=&quot;r+b&quot;)
        ///raw &lt;- rawConnectionValue(zzSOTB)
        ///close(zzSOTB)
        ///rm(&quot;zzSOTB&quot;)
        ///raw.
        /// </summary>
        internal static string FMT_SAVE_OBJECT_TO_BINARY {
            get {
                return ResourceManager.GetString("FMT_SAVE_OBJECT_TO_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rvis_nFactors &lt;- length(rvis_factors)
        ///rvis_omega &lt;- NULL
        ///
        ///if (rvis_omegaFromCukier)
        ///{
        ///  rvis_omega &lt;- fast::freq_cukier(rvis_nFactors)
        ///  if (0 == rvis_sampleSize)
        ///  {
        ///    rvis_maxOmega &lt;- max(rvis_omega)
        ///    rvis_sampleSize &lt;- rvis_maxOmega * rvis_nFactors + 1
        ///  }
        ///}
        ///
        ///if (0 == rvis_sampleSize) rvis_sampleSize &lt;- 1000
        ///
        ///rvis_fast99 &lt;- sensitivity::fast99(
        ///  model = NULL, 
        ///  factors = rvis_factors, 
        ///  n = rvis_sampleSize, 
        ///  M = 4, 
        ///  omega = rvis_omega, 
        ///  q = rvis_distributions, 
        ///  q.arg = rvis_distributionLi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RFRAG_FAST99 {
            get {
                return ResourceManager.GetString("RFRAG_FAST99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rvis_morris &lt;- sensitivity::morris(
        ///  factors = rvis_factors,
        ///  r = rvis_r,
        ///  design = list(type = &quot;oat&quot;, levels = rvis_levels, grid.jump = rvis_gridJump),
        ///  binf = rvis_binf,
        ///  bsup = rvis_bsup,
        ///  scale = rvis_scale
        ///).
        /// </summary>
        internal static string RFRAG_MORRIS_OAT {
            get {
                return ResourceManager.GetString("RFRAG_MORRIS_OAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rvis_morris &lt;- sensitivity::morris(
        ///  factors = rvis_factors,
        ///  r = rvis_r,
        ///  design = list(type = &quot;simplex&quot;, scale.factor = rvis_scaleFactor),
        ///  binf = rvis_binf,
        ///  bsup = rvis_bsup,
        ///  scale = rvis_scale
        ///).
        /// </summary>
        internal static string RFRAG_MORRIS_SIMPLEX {
            get {
                return ResourceManager.GetString("RFRAG_MORRIS_SIMPLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par(mar=c(3,3,2,0.5), mgp=c(1.5,0.5,0))
        ///plot(
        ///  rvis_morrisMuStar, 
        ///  rvis_morrisSigma, 
        ///  cex.lab=0.8, 
        ///  cex.axis=0.8, 
        ///  cex.main=0.8, 
        ///  xlab=rvis_xlab, 
        ///  xlim=rvis_xlim,
        ///  ylab=rvis_ylab, 
        ///  ylim=rvis_ylim,
        ///  log=&quot;xy&quot;,
        ///  main=rvis_main
        ///  )
        ///text(
        ///  rvis_morrisMuStar, 
        ///  rvis_morrisSigma, 
        ///  labels=rvis_morrisFactors, 
        ///  cex= 0.7, 
        ///  pos=1
        ///  ).
        /// </summary>
        internal static string RSTAT_PLOTMORRIS {
            get {
                return ResourceManager.GetString("RSTAT_PLOTMORRIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par(mar=c(3,3,2,0.5), mgp=c(1.5,0.5,0))
        ///plot(
        ///  c(rvis_xMin, rvis_xMax), 
        ///  c(rvis_yMin, rvis_yMax), 
        ///  type=&quot;n&quot;, 
        ///  cex.lab=0.8, 
        ///  cex.axis=0.8, 
        ///  cex.main=0.8, 
        ///  xlab=rvis_xlab, 
        ///  ylab=rvis_ylab, 
        ///  main=rvis_main
        ///  ).
        /// </summary>
        internal static string RSTAT_PLOTSA {
            get {
                return ResourceManager.GetString("RSTAT_PLOTSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legend(
        ///  &quot;topright&quot;, 
        ///  inset=0.05, 
        ///  cex=0.7, 
        ///  rvis_legend,
        ///  col=rvis_col, 
        ///  lty=c(1,1), 
        ///  lwd=c(2,2), 
        ///  bg=&quot;grey96&quot;
        ///  ).
        /// </summary>
        internal static string RSTAT_SALEGEND {
            get {
                return ResourceManager.GetString("RSTAT_SALEGEND", resourceCulture);
            }
        }
    }
}
