//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVis.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RVis.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is above the specified range.
        /// </summary>
        internal static string ERR_ABOVE_RANGE {
            get {
                return ResourceManager.GetString("ERR_ABOVE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is below the specified range.
        /// </summary>
        internal static string ERR_BELOW_RANGE {
            get {
                return ResourceManager.GetString("ERR_BELOW_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objects are equal.
        /// </summary>
        internal static string ERR_EQUAL {
            get {
                return ResourceManager.GetString("ERR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is infinite.
        /// </summary>
        internal static string ERR_INFINITE {
            get {
                return ResourceManager.GetString("ERR_INFINITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not a number (NaN).
        /// </summary>
        internal static string ERR_NAN {
            get {
                return ResourceManager.GetString("ERR_NAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numbers are not equal, within the specified tolerance.
        /// </summary>
        internal static string ERR_NOT_ALMOST_EQUAL {
            get {
                return ResourceManager.GetString("ERR_NOT_ALMOST_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objects are not equal.
        /// </summary>
        internal static string ERR_NOT_EQUAL {
            get {
                return ResourceManager.GetString("ERR_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition is not false.
        /// </summary>
        internal static string ERR_NOT_FALSE {
            get {
                return ResourceManager.GetString("ERR_NOT_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is not null.
        /// </summary>
        internal static string ERR_NOT_NULL {
            get {
                return ResourceManager.GetString("ERR_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition is not true.
        /// </summary>
        internal static string ERR_NOT_TRUE {
            get {
                return ResourceManager.GetString("ERR_NOT_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is null.
        /// </summary>
        internal static string ERR_NULL {
            get {
                return ResourceManager.GetString("ERR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is not null or empty.
        /// </summary>
        internal static string ERR_STRING_NOT_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERR_STRING_NOT_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is null or empty.
        /// </summary>
        internal static string ERR_STRING_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERR_STRING_NULL_OR_EMPTY", resourceCulture);
            }
        }
    }
}
